-- MySQL Script generated by MySQL Workbench
-- Mon Oct 20 19:03:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat2date
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat2date` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

USE `chat2date` ;

-- -----------------------------------------------------
-- Table `chat2date`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`user` (
  `userId` VARCHAR(36) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(10) NULL DEFAULT NULL,
  `provider` ENUM('GOOGLE', 'OTP') NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(30) NOT NULL,
  `cardId` VARCHAR(13) NOT NULL,
  `birthday` DATE NOT NULL,
  `sex` ENUM('MALE', 'FEMALE') NOT NULL,
  `behaviorScore` INT NOT NULL DEFAULT '0',
  `isBlacklist` TINYINT NOT NULL DEFAULT false,
  `accountStatus` ENUM('ACTIVE', 'SUSPENDED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  `version` INT NOT NULL,
  `role` ENUM('USER', 'ADMIN') NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `Email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `PhoneNumber` (`phoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `cardId` (`cardId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`action` (
  `actionId` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(36) NOT NULL,
  `actionType` ENUM('LIKE', 'DISLIKE') NOT NULL,
  `targetUserId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`actionId`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  INDEX `targetUserId` (`targetUserId` ASC) VISIBLE,
  UNIQUE INDEX `actionId_UNIQUE` (`actionId` ASC) VISIBLE,
  CONSTRAINT `actiontable_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE,
  CONSTRAINT `actiontable_ibfk_2`
    FOREIGN KEY (`targetUserId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`emergencycontact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`emergencycontact` (
  `emergencyId` INT NOT NULL AUTO_INCREMENT,
  `telephoneNumber` VARCHAR(10) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`emergencyId`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `emergencycontact_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`interest` (
  `interestId` INT NOT NULL AUTO_INCREMENT,
  `interest` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`interestId`),
  UNIQUE INDEX `interest_UNIQUE` (`interest` ASC) VISIBLE,
  UNIQUE INDEX `interestId_UNIQUE` (`interestId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`lifestyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`lifestyle` (
  `lifestyleId` INT NOT NULL AUTO_INCREMENT,
  `lifeStyle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`lifestyleId`),
  UNIQUE INDEX `lifestyle_UNIQUE` (`lifestyle` ASC) VISIBLE,
  UNIQUE INDEX `lifestyleId_UNIQUE` (`lifestyleId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`match` (
  `matchId` INT NOT NULL AUTO_INCREMENT,
  `userId1` VARCHAR(36) NOT NULL,
  `userId2` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`matchId`),
  INDEX `userId1` (`userId1` ASC) VISIBLE,
  INDEX `userId2` (`userId2` ASC) VISIBLE,
  UNIQUE INDEX `matchId_UNIQUE` (`matchId` ASC) VISIBLE,
  CONSTRAINT `matchtable_ibfk_1`
    FOREIGN KEY (`userId1`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE,
  CONSTRAINT `matchtable_ibfk_2`
    FOREIGN KEY (`userId2`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`preferencematch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`preferencematch` (
  `preferenceId` INT NOT NULL AUTO_INCREMENT,
  `interestedGender` ENUM('MALE','FEMALE','BOTH') NOT NULL,
  `interestedTravelStyle` ENUM('SAME', 'NEARLY', 'UNRELATED', 'UNNECESSARY') NOT NULL,
  `interestedLifeStyle` ENUM('SAME', 'NEARLY', 'UNRELATED', 'UNNECESSARY') NOT NULL,
  `interestedInterest` ENUM('SAME', 'NEARLY', 'UNRELATED', 'UNNECESSARY') NOT NULL,
  `interestedAgeMin` INT NOT NULL,
  `interestedAgeMax` INT NOT NULL,
  `interestedDistanceMin` INT NOT NULL,
  `interestedDistanceMax` INT NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`preferenceId`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  CONSTRAINT `preferencematch_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`tag` (
  `tagId` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`tagId`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC) VISIBLE,
  UNIQUE INDEX `tagId_UNIQUE` (`tagId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`userlocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`userlocation` (
  `locationId` INT NOT NULL AUTO_INCREMENT,
  `latitude` DECIMAL(11,8) NOT NULL,
  `longtitude` DECIMAL(11,8) NOT NULL,
  `accuracy` DECIMAL(6,2) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`locationId`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  CONSTRAINT `userlocation_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`travelstyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`travelstyle` (
  `travelId` INT NOT NULL AUTO_INCREMENT,
  `travelStyle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`travelId`),
  UNIQUE INDEX `travelId_UNIQUE` (`travelId` ASC) VISIBLE,
  UNIQUE INDEX `travelStyle_UNIQUE` (`travelStyle` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`userphoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`userphoto` (
  `photoId` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(36) NOT NULL,
  `attributes` JSON NOT NULL,
  `base64Card` LONGTEXT, 
  PRIMARY KEY (`photoId`),
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `userphoto_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`user_has_travelstyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`user_has_travelstyle` (
  `user_userId` VARCHAR(36) NOT NULL,
  `travelstyle_travelId` INT NOT NULL,
  PRIMARY KEY (`user_userId`, `travelstyle_travelId`),
  INDEX `fk_user_has_travelstyle_travelstyle1_idx` (`travelstyle_travelId` ASC) VISIBLE,
  INDEX `fk_user_has_travelstyle_user1_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_travelstyle_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_travelstyle_travelstyle1`
    FOREIGN KEY (`travelstyle_travelId`)
    REFERENCES `chat2date`.`travelstyle` (`travelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`user_has_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`user_has_interest` (
  `user_userId` VARCHAR(36) NOT NULL,
  `interest_interestId` INT NOT NULL,
  PRIMARY KEY (`user_userId`, `interest_interestId`),
  INDEX `fk_user_has_interest_interest1_idx` (`interest_interestId` ASC) VISIBLE,
  INDEX `fk_user_has_interest_user1_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_interest_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_interest_interest1`
    FOREIGN KEY (`interest_interestId`)
    REFERENCES `chat2date`.`interest` (`interestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`user_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`user_has_tag` (
  `user_userId` VARCHAR(36) NOT NULL,
  `tag_tagId` INT NOT NULL,
  PRIMARY KEY (`user_userId`, `tag_tagId`),
  INDEX `fk_user_has_tag_tag1_idx` (`tag_tagId` ASC) VISIBLE,
  INDEX `fk_user_has_tag_user1_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_tag_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_tag_tag1`
    FOREIGN KEY (`tag_tagId`)
    REFERENCES `chat2date`.`tag` (`tagId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`user_has_lifestyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`user_has_lifestyle` (
  `user_userId` VARCHAR(36) NOT NULL,
  `lifestyle_lifestyleId` INT NOT NULL,
  PRIMARY KEY (`user_userId`, `lifestyle_lifestyleId`),
  INDEX `fk_user_has_lifestyle_lifestyle1_idx` (`lifestyle_lifestyleId` ASC) VISIBLE,
  INDEX `fk_user_has_lifestyle_user1_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_lifestyle_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_lifestyle_lifestyle1`
    FOREIGN KEY (`lifestyle_lifestyleId`)
    REFERENCES `chat2date`.`lifestyle` (`lifestyleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chat2date`.`devicetoken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat2date`.`devicetoken` (
  `devicetokenId` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(36) NOT NULL,
  `fcmToken` VARCHAR(512) NOT NULL,
  `platform` VARCHAR(20) NULL,              -- android / ios
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`devicetokenId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `devicetoken_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `chat2date`.`user` (`userId`)
    ON DELETE CASCADE,
  UNIQUE INDEX `uk_user_token` (`userId`, `fcmToken`) VISIBLE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
