// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL6izg9weZrUkxe4UFuzXWSs5U-DTc0Xc',
    appId: '1:671859491710:web:e4bbe140b521f137ffa92f',
    messagingSenderId: '671859491710',
    projectId: 'chat2date-46e6c',
    authDomain: 'chat2date-46e6c.firebaseapp.com',
    storageBucket: 'chat2date-46e6c.firebasestorage.app',
    measurementId: 'G-G4B9GB4HNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkENMA71teuffn8l9OiePa3FdgM3Lepw8',
    appId: '1:671859491710:android:d3e64fd75c0e9e66ffa92f',
    messagingSenderId: '671859491710',
    projectId: 'chat2date-46e6c',
    storageBucket: 'chat2date-46e6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdRcQywrh5CFb_Gbz9lJEiUgz2BJN3Ms',
    appId: '1:671859491710:ios:9c7d97b05e408797ffa92f',
    messagingSenderId: '671859491710',
    projectId: 'chat2date-46e6c',
    storageBucket: 'chat2date-46e6c.firebasestorage.app',
    iosBundleId: 'com.fujipp.chat2date',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHdRcQywrh5CFb_Gbz9lJEiUgz2BJN3Ms',
    appId: '1:671859491710:ios:1b668e407be03434ffa92f',
    messagingSenderId: '671859491710',
    projectId: 'chat2date-46e6c',
    storageBucket: 'chat2date-46e6c.firebasestorage.app',
    iosBundleId: 'com.example.chat2date',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL6izg9weZrUkxe4UFuzXWSs5U-DTc0Xc',
    appId: '1:671859491710:web:03c95167881f2b92ffa92f',
    messagingSenderId: '671859491710',
    projectId: 'chat2date-46e6c',
    authDomain: 'chat2date-46e6c.firebaseapp.com',
    storageBucket: 'chat2date-46e6c.firebasestorage.app',
    measurementId: 'G-T5HD4G15MQ',
  );
}
