smsmkt:
  apiKey: "f6fa786eabdb337cb324c56b091c2788"
  secretKey: "gp8dxiYyvqEkd3rg"
  projectKey: "6a1937bbc1"

server:
  address: 0.0.0.0
  port: 8080
  tomcat:
    connection-timeout: 10s

spring:
  mvc:
    cors:
      mappings:
        "[/api/**]":
          allowed-origins: "*"
          allowed-methods: "GET,POST,OPTIONS"
          allowed-headers: "*"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
